name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ".[dev]"

      - name: Lint (ruff)
        run: ruff check e2neutrino tests

      - name: Type check (mypy)
        run: mypy e2neutrino

      - name: Run tests
        run: pytest

      - name: Build distribution
        run: python -m build

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: e2neutrino-dist
          path: dist/*
          if-no-files-found: error
