name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install toolchain
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -e . --no-deps

      - name: Lint (ruff)
        run: ruff check .

      - name: Test (pytest)
        run: pytest -q

      - name: Type check (mypy)
        run: mypy e2neutrino
        continue-on-error: true

      - name: Build distribution
        run: python -m build

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: e2neutrino-dist
          path: dist/*
          if-no-files-found: error
