name: Release

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_PUSH_NEUTRINO_SETTINGS }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
