name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      RELEASE_PLEASE_TOKEN: ${{ secrets.PAT_PUSH_NEUTRINO_SETTINGS != '' && secrets.PAT_PUSH_NEUTRINO_SETTINGS || secrets.ENV_GLOBAL != '' && secrets.ENV_GLOBAL || vars.ENV_GLOBAL }}
    steps:
      - name: Ensure release token present
        run: |
          if [ -z "${RELEASE_PLEASE_TOKEN:-}" ]; then
            echo "Release token not configured. Please set PAT_PUSH_NEUTRINO_SETTINGS or ENV_GLOBAL (secret or variable)." >&2
            exit 1
          fi
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ env.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
